---
title: "Vocab, readings: Week 7, 8, and some of week 9 lectures on Stats and Studies"
date: "This document may be updated as the lectures proceed."
output: html_document
---

For the words on this page that are underlined with tiny dots, a short definition will pop up if you hover over the word with your mouse pointer. Here's an example:  <abbr title="Alex is a middle-aged man who is lecturing from weeks 7 to 13.">Alex</abbr>. To study, first ask yourself on what the word means, and then check whether you're right by hovering over the word.

## Important Readings

* [Planet Money podcast](https://www.npr.org/transcripts/178635250) on causation and correlation. Study questions:
  * Why did women take hormone replacement therapy?
  * What kind of study was done to better assess the effect of hormone replacement therapy?
    * Why was this study better than the first evidence that led hormone replacement therapy to originally start?

* [Khan Academy](https://www.khanacademy.org/math/probability/scatterplots-a1/creating-interpreting-scatterplots/v/correlation-and-causality) on correlation and causality. Study questions:
  * Khan talks about an article that suggests that eating breakfast prevents obesity. He also suggests alternative causal models. Name one.

*  [Alex on the ways the word "control" is used](https://alexholcombe.github.io/teachingATHK/readings/controllingForVsControl.html) and random assignment.

* Another [explanation of random assignment](http://isps.yale.edu/node/16697).

* [What is a confounding variable?](http://www.statisticshowto.com/design-of-experiments/confounding-variable/)


<!-- Critical Thinking, by Paul and Elder -->

## Not-so-important Readings

* [Why is nutrition so hard to study?](https://www.medicalnewstoday.com/articles/why-is-nutrition-so-hard-to-study)

* Chapter 4, Correlation, of *Naked Statistics* (already recommended by Bruce)

* To understand how regression can "control for" an extraneous variable, read *Naked Statistics* Chapter 11 and the “Highly correlated explanatory variables” in Ch.12.

* [r-squared](http://blog.minitab.com/blog/adventures-in-statistics/regression-analysis-how-do-i-interpret-r-squared-and-assess-the-goodness-of-fit)

* https://alexholcombe.wordpress.com/2016/02/03/problems-with-controlling-for-variables-quick-notes/ The first few paragraphs are helpful for explaining "controlling for", but then it quickly becomes more complex and more advanced than is needed for this unit.

* TEDxDHFastStream - Dr Ben Goldacre talking about [randomised controlled trials for public policy](https://www.youtube.com/watch?v=RzRs7cPrrfE)

# Vocabulary (partial list, see more terms on the [Lectures outline](https://alexholcombe.github.io/teachingATHK/outline.html))

* Correlation, used in this class to refer only to linear correlation.
* Linear growth (black) versus exponential growth (blue).

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.height=2.5, fig.width=2.5,  fig.cap = "" }
start<-10; pctIncrease<-10
xs<-seq(0,20)
ys<-2*xs +start
expo<-xs
expo[1]<-start
for(i in 2:length(xs)) {
  expo[i] <- expo[i-1]*(1+pctIncrease/100)
}
library(tibble); library(plyr); library(ggplot2)
ddd<-tibble(x=xs,y=ys,expo=expo)
h<-ggplot( data = ddd, aes( x, y )) + geom_point() + theme_bw() + ylab("cases in Australia") + xlab('day') +
          geom_point(aes(x = x, y = expo), color = "blue", alpha=.6) + scale_x_continuous(breaks = seq(0, 20, by = 4))
show(h)
```

* <abbr title="Study that is NOT an experiment (no experimenter manipulation of critical variable, or random assignment of people to one of e.g. two groups)">Observational study</abbr> Observational studies are sometimes referred to as correlational studies.
* <abbr title="A study where the researcher manipulates the critical variable that they want to know the effect of (might not be true for 'Quasi-' or 'natural' experiments, which are different)">Experiment</abbr> 
* Quasi / natural experiment
* Random assignment ([explainer](http://isps.yale.edu/node/16697))
* r
<!-- * r-squared and shared variance
* Proportion of variance explained, shared variance
 Squaring r gives the proportion of variance explained by the line. "Shared variance" is a synonym.-->

### Variables
* <abbr title="Independent variable. A variable manipulated in an experiment.">IV</abbr>, <abbr title="Dependent variable. A measured (not manipulated variable)">DV</abbr>
* "the intervention" refers to the independent variable
* Explanatory variable
* <abbr title="Refers to a variable that was not included in an analysis but might be important.">Extraneous variable</abbr> 
<!-- When one compares two groups, one is seeking to determine the effect of an explanatory variable or variables. But extraneous variables are variables that also differ between the two groups. They may be confounds. -->
* <abbr title="When one compares two groups, ideally only one thing (the independent variable, if an experiment) differs. A confound is something else that differs which might be the cause of the difference.">Confound or confounding variables</abbr> 
<!-- Confounds are sometimes known as omitted variables in the context of observational studies or in the context of a statistical model like a regression. In experiment design, you might be interested in the effect of videogames on agression. You recruit a group of videogamers and another group of non-gamers and assess their agression level (somehow). You find that the videogamers are more agressive. Does this mean that videogaming causes agression? No, because you might have a confounding variable like age. Videogamers tend to be younger so your videogaming group may be younger than your non-gaming group. And, aggression levels decrease with age (and this was true even before videogames was invented), meaning that perhaps the only reason gamers are more violent is because they are younger. 
http://www.statisticshowto.com/design-of-experiments/confounding-variable/
-->
* [Nuisance variable](https://dictionary.apa.org/nuisance-variable) or noise variable versus confound
* <abbr title="Used in the context of observational studies, Bruce used it to refer to a problematic variable that in an experimental study would be referred to as a 'confound'">Omitted variable</abbr>

* <abbr title="Using statistics to try to 'subtract out' the effect of an extraneous variable or confound, to reveal the causal relationship between IV and DV without contamination by the confound">"Controlling for" a variable</abbr>. Explained [here](https://alexholcombe.wordpress.com/2016/02/03/problems-with-controlling-for-variables-quick-notes/), in more detail than you need to know.
<!--This was in Bruce and Alex's lectures and means a confound that you try to compensate for using statistics, to reveal the causal relationship between IV and DV without contamination by the confound. Usually happens in observational studies but can sometimes happen in experiments.
-->

* <abbr title="In a tutorial, we used this to mean a variable that you ensure does *not* differ between two groups you are comparing. This is in distinction to the independent variable, which is a variable you *do* want to differ between the two groups">Controlled variable</abbr>


### Other terms
* <abbr title="Correlation between X and Y that one might think is due to X causing Y, or Y causing X, but isn't.">Spurious correlation</abbr>
* Causal model
* The [third-cause fallacy](https://apologetics.fandom.com/wiki/Third-cause_fallacy)
* Contingency table
* Residual
* Nonlinear model
* False positive, true positive, false negative, true negative
* <abbr title="Of those without what's being tested for, the proportion that correctly get a NEGATIVE test result. High specificity means low false positive rate" >Specificity</abbr> and <abbr title="How often a test correctly generates a positive result for cases that have what's being tested for (also known as the 'true positive' rate)">sensitivity</abbr>

