---
title: "Causal words"
format: html
editor: visual
---

Below is a list of some common words that are used to communicate causation. 

| Word       | Example phrase where the word implies causation                                   |
|------------|------------------------------------------------------------|
| Cause      | Aging causes hair loss                                     |
| Prevent    | Weight-bearing exercise prevents bone loss                 |
| Affect     | Pressure affects density                                   |
| Protect    | Vitamin C protects against scurvy                          |
| Influence  | Alcohol influences sleep quality                           |
| Improve    | Reading improves vocabulary                                |
| Increase   | Swimming increases risk of bacterial infection             |
| Impacts    | Excercise impacts heart health                             |
| Leads to   | Drinking alcohol leads to liver failure                    |
| Due        | His jaundice is due to malnutrition                        |
| Attribute  | His unhappiness can be attributed to his loss of his money |
| Result     | The result of the scandal was that she had to resign       |
| Reduce     | Coaching reduces anxiety                                   |
| Determines | Strength determines amount of weight you can lift          |
| Benefit    | Caffeine has a benefit of alertness                        |
| Alter      | Probiotics alter the gut biome                             |
| Decrease   | Tolls decrease road use                                    |
| Enhance    | Lacquer enhances appearance                                |
| Elevate    | Financial rewards elevate motivation                       |
| Change     | Punishments change cooperativity                           |

<BR><BR><BR>

There are more words used to communicate causation, but the above are the most common ones (see e.g. ["Causal and Associational Language in Observational Health Research: A Systematic Evaluation"](https://pubmed.ncbi.nlm.nih.gov/35925053/) )