---
title: "ATHK1001 Logic and Arguments tutorial 2 of 2"
date: "weeks of 15 May, 2017"
output: html_document
---
<!-- ALEX for 2017: number the questions, make it shorter or indicate what parts are optional
Student machines have youtube blocked, says Bruce.
-->

<!-- TUTORS: there are explanations and additional examples of the topics below in the lecture slides.
* You should have the lecture slides at the ready to go back through, when it's clear some students don't understand something.
* Also be aware of the ArgumentsIntroHandout on eLearning, and the Vocab_and_Readings handout on eLearning
* I suggest doing the first two syllogisms together as a class, and then having them do a bunch together in pairs, before discussing them again as a class.

-->

### Learning Outcomes for this and the previous tutorial

**Understand**: 

Tutorial 1. Necessary and sufficient, Validity, Soundness, If-then statements, Syllogisms

Tutorial 2. Real-world syllogisms, Deduction versus Induction, Strong, Cogent, and Circularity.

<BR>


### Syllogisms: Realistic forms

<BR>
In real prose and conversations, if-then statements are pretty uncommon. Most logical arguments even in the real world still boil down to if-then type statements, so if you can recognise them, you'll do better in evaluating arguments.

> No wealthy persons are vagrants. All lawyers are rich. Therefore no attorneys are homeless.

On a strict definition, this is not a syllogism because the three sentences may be talking about different kinds of people (the wealthy, the rich, lawyers, and attorneys), but probably the author meant wealthy and rich as synonyms, lawyers and attorneys as synonyms, and vagrants and homeless as synonyms.  

1. If you assume that those terms are synonyms, is this a valid syllogism?  NO / YES / INADEQUATE INFORMATION

<BR><BR>

***

In natural writing or speaking, people will completely leave out a premise when it is considered obvious. This is called an **enthymeme**, e.g.

> Socrates is mortal because he's human.

The full form, including the omitted first premise, is:

Premise:  All humans are mortal.  
Premise: Socrates is human.   
Conclusion: Therefore, Socrates is mortal.  

***
<BR><BR>

Below is another **enthymee**, an example of how arguments tend to be condensed in natural writing. Please rewrite it as two premises and a conclusion:

> We know the reactor core had breached, because the coolant pressure level was below the critical value for 10 hours. 


<br><br>
2. Premise: __________________________________________________________________
<!-- If the coolant pressure level is below critical for 10 hours, the reactor core has breached. -->
<BR><BR><BR>
3. Premise: ___________________________________________________________________
<!-- The coolant pressure level was below critical for 10 hours. -->
<BR><BR><BR>
4. Conclusion: ___________________________________________________________________  
<!-- The reactor core had breached. -->

***

> Bill didn't go to work this morning, because he wore a sweater, and he never wears a sweater to work.

This is a condensed syllogism or enthymeme. Please rewrite it below as two premises and a conclusion:

<!-- If Bill goes to work, he does not wear a sweater. 
Bill wore a sweater.    (not B, denying the consequent)
Bill didn't go to work.-->

<br><br>
5. Premise: __________________________________________________________________
<BR><BR><BR>
6. Premise: ___________________________________________________________________
<BR><BR><BR>
7. Conclusion: ___________________________________________________________________  

<BR>
8. Is the above syllogism *valid*?  NO / YES  

***

> Mallory is a canine because she is a dog.

Rewrite the above sentence as a syllogism:
<BR><BR><BR>
9. Premise: ___________________________________________________________________
<!--If something is a dog, it is a canine-->
<BR><BR><BR>
10. Premise: ___________________________________________________________________
<!--Mallory is a dog-->
<BR><BR><BR>
11. Conclusion: ___________________________________________________________________
<!--Therefore, Mallory is a canine.-->
<BR><BR>
12. Is the above syllogism *valid*? ____________ 
13. Is it *sound*? ______________  

***


Below is the start of a syllogism. Please complete it with a valid conclusion:

>Sydney vacancy rates exceed 6%. Whenever the rate exceeds 6%, you can be sure that there are some great deals on rentals near campus. Therefore,

14. ______________________________________________________________  


Is the above syllogism sound? ___________________________ 
<!--Ask them whether in their experience, apartment rental prices are inexpensive near campus.
(By world and Australian standards, they are expensive)

Ask them how they could you find out whether the argument is sound.
(This is purely to get them talking about a real-world issue; doing this research is not related to the class)

They need to check both of the premises. 
Checking the second premise authoritatively would require extensive knowledge of economics and relevant studies.
To check the first premise, in Google News you can search for "Sydney vacancy rate" and find an article like
this:
http://www.domain.com.au/news/sydneys-surprising-underperforming-market-domain-group-20160311-gng2g4/
which shows that vacancy rates in Sydney are well below 3%. So the first premise is false.

Of course, that doesn't mean the conclusion is false, just that it does not follow from these particular premises, as at least one premise is false. The conclusion might still happen to be true for other reasons.
-->

***  

> If everyone in Victoria drank red wine daily, then the wine industry would be booming. But many Victorians never drink wine. So, the wine industry is not booming.

15. Is the above syllogism *valid*? ____________ 
16. Is it *sound*? ______________
<!--The structure of the argument is: If A then B. A is false. Therefore B is false.
This is a fallacy, because it doesn't exclude that B (booming wine industry) might be true for other reasons.
This is called the fallacy of denying the antecedent (in Alex's slides, and in the tute table)-->

17. According to the above syllogism, everyone in Victoria drinking red wine daily is:

A) Necessary for the wine industry to boom
B) Sufficient for the wine industry to boom
C) Necessary and sufficient for the wine industry to boom

<!-- sufficient -->

*****

Read the below poem written around the year 1649 by Andrew Marvell.

#### *To his coy mistress* 

Had we but world enough and time,  
This coyness, lady, were no crime.  
We would sit down, and think which way  
To walk, and pass our long love’s day.  
Thou by the Indian Ganges’ side  
Shouldst rubies find; I by the tide  
Of Humber would complain. I would  
Love you ten years before the flood,  
And you should, if you please, refuse  
Till the conversion of the Jews.  
My vegetable love should grow  
Vaster than empires and more slow;  
An hundred years should go to praise  
Thine eyes, and on thy forehead gaze;  
Two hundred to adore each breast,  
But thirty thousand to the rest;  
An age at least to every part,  
And the last age should show your heart.  
For, lady, you deserve this state,  
Nor would I love at lower rate.  
But at my back I always hear  
Time’s wingèd chariot hurrying near;  
And yonder all before us lie  
Deserts of vast eternity.  
Thy beauty shall no more be found;  
Nor, in thy marble vault, shall sound  
My echoing song; then worms shall try  
That long-preserved virginity,  
And your quaint honour turn to dust,  
And into ashes all my lust;  
The grave’s a fine and private place,  
But none, I think, do there embrace.  
Now therefore, while the youthful hue  
Sits on thy skin like morning dew,  
And while thy willing soul transpires  
At every pore with instant fires,  
Now let us sport us while we may,  
And now, like amorous birds of prey,  
Rather at once our time devour  
Than languish in his slow-chapped power.  
Let us roll all our strength and all  
Our sweetness up into one ball,  
And tear our pleasures with rough strife  
Through the iron gates of life:  
Thus, though we cannot make our sun  
Stand still, yet we will make him run.  
<br>
Can you boil down Marvell's argument into two premises and a conclusion?
<br><br>
18. Premise: __________________________________________________________________
<BR><BR><BR>
19. Premise: ___________________________________________________________________
<BR><BR><BR>
20. Conclusion: ___________________________________________________________________
<!--Premise: if we had world enough and time, your coyness would be tolerable; 
Premise: we do not have sufficient world or time
Conclusion: therefore, we must do *it* now.
-->
<BR><BR>

### Deduction versus induction

>The American president lives in the White House. Hilary Clinton is the American president. Therefore, Hilary Clinton lives in the White House.

21. Is the above syllogism *valid*? ____________ 
22. Is it *sound*? ______________

23. What makes the above argument's conclusion false? _____________  
<!-- The second premise is false. -->

24. What makes the above sentences a syllogism?  
<!-- It is a deductive argument made up of two premises and a conclusion -->  

*****  
>Almost all things that Donald Trump says about himself are false. Donald Trump said, "I have normal-sized fingers". Therefore Donald Trump does not have normal-sized fingers.

25. Do the above sentences form a syllogism? _________________
<!-- No, because they are not deductive. They are inductive. They form an inductive argument.-->
<!-- The first Clinton argument is a syllogism. The second one isn't because it relies on probabilistic support, indicated by "Most".-->

*****  
### Valid is to Strong as Cogent is to Strong  

For *inductive* arguments, the term for logically consistent is **cogent** rather than **valid**- "valid" is used only for deductive arguments. 
The counterpart to the term *sound* (in deduction, used for both the premises being true and the argument logically consistent) is "strong" for induction. 
For an inductive argument to be strong, both the premises must be true and the argument must be cogent.

26. Returning to the Trump argument, is it *cogent*? ____________
<!-- Yes -->
27. Is it *strong*? ___________
<!-- Not sure 
 The Trump argument is cogent and good if the premises are true. But possibly the first premise is not true.  -->

*****

Whenever something refers to **probable support** rather than certainty, it is **induction**, not **deduction**.
When science presents evidence, it almost never proves something (certainty), instead the best it can do is probable support. Most conclusions in science are therefore inductive.

> Throughout history, the sun has come up every day. Therefore, it will come up tomorrow.

28. Is the above an *inductive* or a *deductive* argument? ______________________

29. Is the above *cogent*? ____________
<!-- Yes -->
30. Is it *strong*? ___________
<!-- Yes  -->

*****

> If you have prostate cancer, very likely the prostate-specific antigen (PSA) level in your blood will exceed 4.0 ng/mL.
The doctor reports that your PSA level is 4.5 ng/mL.
It is very likely that you have prostate cancer.

31. Is the conclusion **cogent**? _________________  
<!-- No, because the premises haven't said whether there are other ways that you can have an elevated PSA level.
If there are other ways and they are sufficiently common, then the conclusion is false. 
Making this mistake is analogous, in induction, to the fallacy of affirming the consequent in deduction.
In Bruce's lectures he referred to humans' tendency to neglect the base rate of something. Here, people tend to neglect the possibility that the base rate of people even without cancer having >4.5 ng/mL might be high.
-->
<BR>
32. Is the conclusion **strong**? __________________
<!--No, because it isn't cogent. To be strong, the argument must be cogent AND the premises must be true. 
<!-- You could the students that not only is the argument not cogent, but also the conclusion happens to be false.
Only about one in three men who have an elevated PSA level are found to have cancer (specifically, that subsequent biopsy finds malignancy).
Like many other medical tests, the PSA test is unreliable.
This is a big issue in medicine, such as whether regular screening should be recommended for breast cancer and prostate cancer. The false alarm rate can be high enough that the number of lives saved may be very small relative to the expense of the multiple tests done and the unnecessary surgeries that sometimes occur, which are themselves dangerous.
http://www.uptodate.com/contents/screening-for-prostate-cancer -->

*****

### Deduction, induction, and informal writing

> When I turn the key in the ignition, my car won't start. It’s silent. Therefore, my battery is dead.

Write down the premises and conclusion of this argument. One is implicit:  
<!-- If turning the key in the ignition yields silence, the car battery is dead.
Turning the key in my car's ignition yields silence.
Therefore, the battery is dead -->
<BR><BR>
33. Premise: ____________________________________________________________________________________
 <BR><BR>
34. Premise: ____________________________________________________________________________________
<BR><BR>
35. Conclusion: ____________________________________________________________________________________
<BR><BR>
36. Is the argument deductive or inductive?  _______________________________
<BR><BR>
37. Is the argument sound?  ____________________  38. Are the premises true?   ____________________  

<BR><BR>

The premise that silence upon turning the key means the battery is dead is false - there are other possibilities, like that the battery is not connected. Because the premise is false, the argument is not sound, although it is valid. 

The argument about the car above, as stated, is deductive. However, the writer of the argument probably is aware that other things (like a disconnected battery) could explain the problem, but simply thinks they are much more unlikely than the possibility that the battery is dead. In other words, the writer may actually be reasoning inductively. Language is often used very messily. Humans!

Rewrite the argument to make it clearly inductive:
<!-- If turning the key in the ignition yields silence, **very likely** the car battery is dead.
Turning the key in my car's ignition yields silence.
Therefore, the battery very likely is dead -->
<BR><BR>
39. Premise: ____________________________________________________________________________________
 <BR><BR>
40. Premise: ____________________________________________________________________________________
<BR><BR>
41. Conclusion: ____________________________________________________________________________________
<BR><BR>

42. Is the argument cogent? NO / YES 
<!--Yes, the logic follows -->
43. Do you think the argument is strong? NO / YES
<!--Yes, as far as I know about cars-->

*****

### Informal arguments: Find the main conclusion

People rarely delineate the structure of their arguments as clearly as the previous examples, and multiple premises are provided, embedded in other types of statements.  Some *indicator* words like "therefore", "because", and "since" that can help you identify the premises and conclusion of an argument are listed in Alex's lecture slide. Please **find the main conclusion** in the passages below.

*****

The interests of all, whether high or low, are equal. The members of the working classes are citizens by nature and by the same right as the rich; they are real parts, living the life which makes up, through the family, the body of the commonwealth . . . therefore the public administration must duly and solicitously provide for the welfare and the comfort of the working classes; otherwise, that law of justice will be violated which ordains that each man shall have his due.
– Pope Leo XIII, Rerum Novarum

  a. The interests of all, whether high or low, are equal. 
  b. The members of the working classes are citizens by nature and have the same rights as the rich. 
  c. Public administration must duly and solicitously provide for the welfare and comfort of the working classes.   
  d. Otherwise that law of justice will be violated which ordains that each man shall have his due. 

<!--C  The indicator word “therefore” identifies the conclusion. The rest of the choices are premises.
The "otherwise" phrase is stated last but is nevertheless a premise that contributes to the conclusion, C
-->  

*****

While the 19th-century British idealists read Hegel as an arch-metaphysician of the Absolute, modern Hegelians interpret their idol as a modest pragmatist, resolving metaphysical arguments in the practices of post-Wittgensteinian forms of life. That Hegel can be interpreted in such wildly contrary ways shows that his works are so obscurely written as to be worthless, since they are evidently elastic enough to fit any sort of philosophical agenda.

  a. Modern Hegelians interpret Hegel as a modest pragmatist. 
  b. Hegel is not an arch-metaphysician of the Absolute. 
  c. Hegel can be interpreted in wildly contrary ways. 
  d. Hegel’s works are so obscurely written as to be worthless. 

<!--D. The word “since” is the indicator word showing a premise, "shows" is an indicator word that helps signal the conclusion. The first sentence supports this conclusion by pointing out how Hegel is interpreted in varying ways.
“Since” helps signal that the last phrase is not a conclusion but rather is a premise.
"Hegel can be interpreted in wildly contrary ways", option C, is an intermediate conclusion from some of the premises that then leads to the final conclusion".
-->
  
*****

My character would never betray his old friend and superior officer. This plot twist is cheap and contrived. You need to rewrite this whole story, because if this goes on, I’m going to quit the show.

Circle the main conclusion.

<!-- "You need to rewrite this whole story".   The indicator word “because” is the best clue to the overall point of the passage. -->

*****

### Begging the question or circularity

[1-minute video introduction](https://www.youtube.com/watch?v=vTVTqjqqhrw)  


Whatever is less dense than water will float, because such objects won't sink in water.  

Why is this statement circular?

***

**Lily**: I can’t understand why the news media give so much coverage to Kim Kardashian. It’s ridiculous. She’s not that important or newsworthy.

**Beth**: What? Of course she’s important and newsworthy! Kim Kardashian is a big deal. Why, just turn on the television. Newspapers, the ABC, you name it. She’s everywhere.

**Lily**: That begs the question.

**Beth**: Huh?

Lily is asking why Kim Kardashian gets so much coverage, but Beth answers by essentially re-stating that Kim Kardashian gets lots of coverage. As Beth did here, in real-world conversation it can be easy to forget or mistake the original question.

***

#### Mark on the speed limit

<BR>
**Mark**: The speed limit should be 110 kph on interstate highways.
Because the motorways were designed for high speed traffic, it is safe to drive at 110 kph.

**Jess**: In America, the accident rate dropped when the speed limit was reduced to 55 mph (89 kph) in the late 1970's, and it has increased since the speed limit was returned to 65 mph (105 kph).

**Mark**: Many people will drive at 110 kph whether or not the legal limit is 100 kph.

Did Jess rebut Mark's claims, assuming that Jess's statement was factually correct?  
<!-- Jess did provide a decent rebuttal of Mark's claim.  However, she didn't say how much exactly the accident rate dropped and increased. Possibly, the rate in both cases is low enough to be considered "safe". Jess and Mark ought to have a discussion of what they consider safe.-->

<BR>
_________________________________________________________________________

<BR>
Did Mark rebut Jess' point?  
<BR> _________________________________________________________________________  
<!-- No, Mark did not say anything that addressed Jess' claim that a higher speed limit is not safe. -->
<BR>
Did Mark effectively defend his initial claim?  
<!--Mark made what may be a valid point, and at first you may think, he scored!
But when you examine the connection to his initial claim, you realize he is not talking about his initial claim anymore, which was that it is safe to drive at 110 kph.

Initially he was making an argument based on safety for raising the speed limit. Jess provided a rebuttal of that, but Mark has not defended his initial claim.

Now Mark is making a completely different argument And it's not clear at this point whether it is a good one.
That is, it is dubious that many people ignoring the speed limit is a good argument for having a low speed limit.

Ask the class their reaction to his new argument.
-->
<BR>
_________________________________________________________________________
<BR>

***

#### Chen on the petrol tax   
**Chen**: The tax on petrol should not be raised significantly,
because the economy will be hurt by higher taxes.

**Isabel**: Taxes could always be lowered in other areas to compensate for the increased petrol tax, and raising the cost of petrol will encourage conservation which would be good for the economy in the long run.

**Chen**: Increased petrol tax would hit lower and middle income people harder than wealthier people, so it would be unfair.

Assume the facts provided by Isabel and Chen are correct.  
<BR>
___________________________________________________________________________________
<BR>  
Did Chen provide an effective rebuttal to Isabel's point?  
<BR>
___________________________________________________________________________________

<BR>  
In what way did Chen address Isabel's point?  
<BR>
___________________________________________________________________________________
<BR>
<!--By giving a new reason. 
Does this mean that his first justification was not a good one,
and he shouldn't have given it?
He hasn't provided anything to dispute Isabel's counter-point, which might mean Isabel has dispelled his point.
-->

<BR>
What do you think Isabel might say next? 

<BR>
___________________________________________________________________________________

<!-- Isabel could use the same sort of criticism to the new point of Chen as she did for Chen's first point.
That is, Isabel could say something like, 
"Other taxes that hit poorer people more could be lowered to compensate for the unfairness."-->

<BR><BR>

What do you think of Chen's position?
<!--There might not be enough here to fairly evaluate Chen's full position.
Unfortunately, this is as far as people in a real-world argument usually get.
Maybe Chen has some good reasons why taxes shouldn't be changed in other areas.
-->
<BR>
___________________________________________________________________________________

<BR>
This is about as far as most arguments get in the media. In a debate on television, people usually only get to say two or three things to each other. But it’s impossible for a person to give all the reasons for their position in such a short time. If we want to fairly evaluate someone's position, we need patience and dedication to the issue.
